### ISSUE TITLE
txn_type of type subscr_signup is generating invalid error logs

### ISSUE THREAD

**Issue by tlfbrito** [snowplow-archive/symfony2-paypal-ipn#17]
When customer pay for a subscription service for the first time, the IPN will ALWAYS create 2 notifications:
- One for the signup of the subscription: txn_type => subscr_signup
- Another one with the payment of the subscription: txn_type => subscr_payment

They can be sent without a specific order.
The subscr_signup will cause an error in the log because it doesn't contain payment_status

More info about subscriptions: http://www.mixedwaves.com/2010/11/paypal-subscriptions-ipn-demystified/

**Comment by alexanderdean** [comment]
Interesting @tiagobrito - not sure what the optimal solution is. Feel free to do a PR!

**Comment by tlfbrito** [comment]
@alexanderdean If you need help resolving this issue, please let me know. I can help you or you can help me with a suggestion to fix this issue and I make a PR

**Comment by alexanderdean** [comment]
Sounds good - @tiagobrito - do you want to come up with a proposal in this thread?

**Comment by tlfbrito** [comment]
Sure. So, the problem is that you log the transaction to catch all future errors (which is great).

``` php
// First thing we do is to log this transaction. This way if the script silently fails, there is still a record of the IPN call.
// (If the script succeeds, or another error occurs, then this error message will be overwritten).
$this->_logTransaction('IPN', 'ERROR', 'Script failed silently, detail field contains the serialized data from PayPal', serialize($ipnDataRaw));
```

But IPN will send an notification (txn_type => subscr_signup) valid but without an $this->ipnData['payment_status']

**Comment by tlfbrito** [comment]
Now we can detect this case and log as a success subscription

``` php
        if (isset($this->ipnData['txn_type']) && $this->ipnData['txn_type'] == 'subscr_signup'){
            $this->_logTransaction('IPN', 'SUCCESS', 'Subscription has been created', $ipnResponse);
            return true;
        }
```

**Comment by alexanderdean** [comment]
Looks good to me - I can't see that interfering with any of the other code.

If you want to put that in a PR @tiagobrito , I will merge

**Comment by tlfbrito** [comment]
PR available here https://github.com/orderly/symfony2-paypal-ipn/pull/19
