### ISSUE TITLE
Enum field

### ISSUE THREAD

**Issue by christianbefore** [snowplow-archive/symfony2-paypal-ipn#2]
Firstly, thanks very much to the Orderly team for this fantastic package!

The 'IpnOrders' entity uses an Enum field, 'orderStatus'. Is there any chance you'll change this from an Enum? It's not widely supported outside MySql, and is the only thing that stops this package working out of the box.

**Comment by alexanderdean** [comment]
Hi christian - thanks for raising this. What database are you working with? It's definitely not our intention to be MySQL-specific...

**Comment by bartoszrychlicki** [comment]
The same problem here, this:

@ORM\Column(name="order_status", type="enumorderstatus", nullable=true)

makes an doctrine exception throw:

Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.  

Im using MySQL, maybe change it to a string?

**Comment by christianbefore** [comment]
Sorry, forgot about this. We are using MySQL but our environment doesn't allow Enum types, can't remember why. But the solution was simply to edit IpnOrders.orm.yml and change the type of "orderStatus" to "string". Works fine after this change.

**Comment by alexanderdean** [comment]
Thanks, updated both the PHP and the `orm.yml` to use a string. Closing.
