### ISSUE TITLE
Wrong decimal places when updating schema with Doctrine

### ISSUE THREAD

**Issue by ivoaz** [snowplow-archive/symfony2-paypal-ipn#3]
When I update schema with `doctrine:schema:update`, `decimal(10,0)` is created instead of `decimal(10,2)`.
Maybe we can specify decimal places in the model?

**Comment by alexanderdean** [comment]
Sounds like a good idea. Do you want to create a pull request?

**Comment by alexanderdean** [comment]
Fixed by @ivoaz's pull request...
