### ISSUE TITLE
Returning INVALID on valid payments, only 5% of the times

### ISSUE THREAD

**Issue by freddyhaddad** [snowplow-archive/symfony2-paypal-ipn#36]
On our IPN we're getting INVALID from Paypal but only 5% of the time.

What could be the problem ?

**Comment by josaliba** [comment]
Same thing happens for me. I noticed that paypal always returns INVALID when a carriage/line break is present (/r/n). When a customer enters address 1 and address 2, paypal concatenates the 2 addresses by adding a carriage/line break between them.
