### ISSUE TITLE
notice error in Ipn.php

### ISSUE THREAD

**Issue by bartoszrychlicki** [snowplow-archive/symfony2-paypal-ipn#7]
Hi there, I've got an error in the bundle:

Notice: Undefined index: txn_id in [...]/vendor/orderly/paypal-ipn-bundle/src/Orderly/PayPalIpnBundle/Ipn.php line 466

**Comment by alexanderdean** [comment]
Sounds like you are not receiving data from PayPal.

**Comment by bartoszrychlicki** [comment]
Hmm, perhaps, that's possible, I was just testing it localy, but still would be good to define this index in code.

**Comment by alexanderdean** [comment]
Happy to accept a pull request!

**Comment by alexanderdean** [comment]
Closing as nothing has happened on this one in 3 months
